### ISSUE TITLE
建议打包为docker容器

### ISSUE THREAD

**Issue by xmusphlkg** [14790897/paper-ai#12]
感谢作者的工作，非常棒的工作。

我尝试在本地使用时发现需要使用npm运行，也许您可以考虑将工作打包为docker容器？
这样子可以直接通过docker环境变量设置API等变量，就像Nextweb一样：https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web?tab=readme-ov-file#docker-recommended

**Comment by 14790897** [comment]
完成了

## 镜像运行
1. 拉取镜像
```sh
docker pull 14790897/paperai:latest
```
2. 运行镜像
```sh
docker run -d -p 3000:3000 \
  -e NEXT_PUBLIC_AI_URL=自定义AI模型地址\
  -e NEXT_PUBLIC_OPENAI_API_KEY=自定义API KEY \
  14790897/paperai:latest
```
