### ISSUE TITLE
Chinese documents are old

### ISSUE THREAD

**Issue by Glyco-Protein** [14790897/paper-ai#25]
Many of the retrieved Chinese documents are old, not from the past year or two, which leads to the generated summaries being outdated theories.

**Comment by 14790897** [comment]
I will address it

**Comment by 14790897** [comment]
I have added a date range selection box, but it currently does not work for arXiv. It is functional for the other two sources, though.
![image](https://github.com/14790897/paper-ai/assets/121866954/c7646ff8-0fa8-4da7-b718-1b216c7051fd)
