### ISSUE TITLE
请问 使用Vercel的怎么更新版本

### ISSUE THREAD

**Issue by Brave126** [14790897/paper-ai#29]
git更新之后，请问使用 Vercel平台的如何进行更新，现在每次都是重新构建一个，谢谢

**Comment by 14790897** [comment]
好的，我会修改流程

**Comment by 14790897** [comment]
已加入自动更新
直接复制了nextweb的实现：https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web?tab=readme-ov-file#enable-automatic-updates
