### ISSUE TITLE
为什么arxiv搜索后没有生成引用？

### ISSUE THREAD

**Issue by Daft-GD** [14790897/paper-ai#31]
<img width="1280" alt="1" src="https://github.com/14790897/paper-ai/assets/50534680/649124f1-54ad-4c67-8f0d-bc67b1df7248">

**Comment by 14790897** [comment]
![image](https://github.com/14790897/paper-ai/assets/121866954/155c62f3-5c25-41fc-b608-8e0c167b565e)
我这边是有的，要不录个视频我看看，是不是点了停止生成？

**Comment by Daft-GD** [comment]
您好 视频附件太大 对方服务器无法接收 要不我见您微信一下~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "14790897/paper-ai"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月12日(星期二) 中午11:12
***@***.***&gt;;
抄送:&nbsp;"2021信工 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [14790897/paper-ai] 为什么arxiv搜索后没有生成引用？ (Issue #31)





 
image.png (view on web)
 我这边是有的，要不录个视频我看看，是不是点了停止生成？

**Comment by 14790897** [comment]
18221521576
