### ISSUE TITLE
网页版一直报错

### ISSUE THREAD

**Issue by 885783558** [14790897/paper-ai#32]
![image](https://github.com/14790897/paper-ai/assets/15685121/9f139129-fd7e-463f-98c5-69ec0f11d612)

**Comment by 14790897** [comment]
这个是什么时候发生的？我之后有修改过

**Comment by 885783558** [comment]
![image](https://github.com/14790897/paper-ai/assets/15685121/ba1cc160-2677-412b-a11f-6d465d2f65f4)
另：登录那块应该也有问题

**Comment by 14790897** [comment]
我去，你好像是老用户，现在已经不用这个api了，要去设置刷新一下选择one.liuweiqing.top

**Comment by 14790897** [comment]
加我微信 18221521576
