### ISSUE TITLE
建议支持第三方API Key的功能增强

### ISSUE THREAD

**Issue by yzlltyyh** [14790897/paper-ai#4]
是否可以考虑新增一个api_base的设置选项，以便支持第三方API Key的使用？

**Comment by 14790897** [comment]
好的

**Comment by 14790897** [comment]
目前在右上角的齿轮settings界面可以修改，
![image](https://github.com/14790897/paper-ai/assets/121866954/6b36e185-e99b-4134-a70e-9f5665a8c9b1)

**Comment by 14790897** [comment]
现在网站可以免费用gpt4哦

**Comment by 14790897** [comment]
请问使用下来体验怎么样或者有什么想法？

**Comment by yzlltyyh** [comment]
![image](https://github.com/14790897/paper-ai/assets/109973085/67e98ac7-9669-4e52-ba12-a9bba25e32af)
不知道是不是我个人的问题，我在使用时遇到了无反应的情况，上方是我接入我自行搭建的oneapi地址的报错日志
下方是默认地址和key询问后控制台的报错
![image](https://github.com/14790897/paper-ai/assets/109973085/77eb7e62-3cb5-4b8e-8016-a3775de39e44)

**Comment by 14790897** [comment]
![image](https://github.com/14790897/paper-ai/assets/121866954/61443884-2afd-4076-9277-6b6ffdeec13b)
我这里是可以的，是在https://www.paperai.life/ 使用的还是自己搭建的呢？

**Comment by 14790897** [comment]
抱歉，我也不知道什么原因，我会再思考

**Comment by 14790897** [comment]
我知道了，在返回的时候，鼠标没有锁定文本框，导致内容无法插入

**Comment by yzlltyyh** [comment]
草，放上去之后就正常使用了╰(*°▽°*)╯
居然是这个原因
