### ISSUE TITLE
关于semantic scholar和pubmed的key

### ISSUE THREAD

**Issue by mofung1** [14790897/paper-ai#41]
想咨询下大佬，这两个网站的key申请地址可否放在https://docs.paperai.life/文档里呢？看了一下semantic scholar似乎是要填写一个申请去获取key，pubmed不是很清楚在哪申请。这两个效果是不是pubmed更好。

**Comment by 14790897** [comment]
semantic：https://www.semanticscholar.org/product/api
pubmed没有api key
